# Generated by Django 3.1.7 on 2021-03-30 14:08

from django.db import migrations, models
import erm.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to=erm.models.Users.upload_photo)),
                ('resume', models.FileField(blank=True, null=True, upload_to=erm.models.Users.upload_file)),
            ],
        ),
    ]
